name: geepers-env
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - pip>=21.3  # https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/#editable-installation
  - git  # for pip install, due to setuptools_scm
  - pandas
  - geopandas-base
  - xarray
  - pyproj
  - rasterio
  - shapely
  - tyro
